# Generated by Django 4.2.5 on 2025-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='section',
            field=models.CharField(default='audit', max_length=255),
        ),
    ]
